name: Read txt files and write to _Blocker.block

on:
  push:
    branches: [ main ]

jobs:
  read-and-write:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Read txt files and write to _Blocker.block
      run: |
        find . -type f -name "*.txt" -exec cat {} + > _Blocker.block
    - name: Commit changes
      run: |
        git config --global user.email "wiensebastian@bs-intra.de"
        git config --global user.name "2324-Wien-Sebastian-BSZ"
        git commit -am "Add _Blocker.block"
        git push
